#!/bin/bash

## Created By Aditya Shakya

rofi -show drun -location 1 -xoffset 10 -yoffset 620 -line-padding 4 -columns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -theme ~/.config/rofi/nord.rasi
